CONFIG_TIMESLICING=n
CONFIG_SYS_POWER_MANAGEMENT=y
CONFIG_DEVICE_POWER_MANAGEMENT=y
CONFIG_DEVICE_IDLE_PM=y
CONFIG_SYS_POWER_SLEEP_STATES=y
CONFIG_SYS_POWER_DEEP_SLEEP_STATES=y
CONFIG_SYS_PM_STATE_LOCK=y
#CONFIG_SYS_PM_MIN_RESIDENCY_SLEEP_1=4000
#CONFIG_SYS_PM_MIN_RESIDENCY_SLEEP_2=8000
#CONFIG_SYS_PM_MIN_RESIDENCY_SLEEP_2=10000
CONFIG_DEBUG=y
CONFIG_STM32_LPTIM_TIMER=y
