CONFIG_TIMESLICING=n
CONFIG_SYS_POWER_MANAGEMENT=y
CONFIG_SYS_POWER_SLEEP_STATES=y
CONFIG_SYS_POWER_DEEP_SLEEP_STATES=n
CONFIG_DEVICE_POWER_MANAGEMENT=y
CONFIG_SYS_PM_STATE_LOCK=y
CONFIG_SYS_PM_POLICY_RESIDENCY=y
CONFIG_SYS_PM_MIN_RESIDENCY_SLEEP_1=2000
CONFIG_SYS_PM_MIN_RESIDENCY_SLEEP_2=3000
CONFIG_SYS_PM_MIN_RESIDENCY_SLEEP_3=4000
CONFIG_DEBUG=y
CONFIG_STM32_LPTIM_TIMER=y
